### ISSUE TITLE
webdev 2.0.6 fails to build basic Angular project

### ISSUE THREAD

**Issue by kankaristo** [dart-lang/webdev#408]
I recently upgraded to webdev 2.0.6 (and Dart 2.3.1), and now all Angular projects fail to build.

Even a basic `stagehand` project fails to build:
```
cd
mkdir -p TestProject
cd TestProject
stagehand web-angular
pub get
webdev build
```

`webdev build` outputs:
```
webdev could not run for this project.
This version of webdev does not support the `build_daemon` protocol used by your version of `build_runner`.
Please add a dev dependency on `build_daemon` with constraint: >=1.0.0 <2.0.0
```

I suppose not adding the `build_daemon` dependency could be a bug in `stagehand`, but after adding that manually to `pubspec.yaml`, running `webdev build` gives:
```
webdev could not run for this project.
The `build_runner` version – 1.1.3 – is not within the allowed constraint – >=1.3.0 <2.0.0.
```

After changing `build_runner` to 1.3.0, running `pub get` gives:
```
Resolving dependencies... (2.3s)
Because no versions of angular_components match >0.11.0 <0.12.0 and
  angular_components 0.11.0 depends on build_config >=0.2.6 <0.4.0,
  angular_components ^0.11.0 requires build_config >=0.2.6 <0.4.0.
And because build_runner >=1.3.4 depends on build_config >=0.4.0 <0.4.1,
  angular_components ^0.11.0 is incompatible with build_runner >=1.3.4.
And because build_runner >=1.3.0 <1.3.5 depends on build_daemon ^0.5.0 and
  TestProject depends on angular_components ^0.11.0, build_runner >=1.3.0
  requires build_daemon ^0.5.0.
So, because TestProject depends on both build_runner ^1.3.0 and build_daemon
  ^1.0.0, version solving failed.
```

Upgrading to the latest version of `angular_components` (0.13.0) gives similar errors, and I can't seem to get any Angular project to build. Dart 2.3.0 and `webdev` 2.0.5 used to work.

So, `webdev` 2.0.6 and Dart 2.3.1 seem to be uncompatible with Angular? Or am I (and `stagehand`) doing something wrong?

Also, please tell me where to move this issue, if this isn't an issue in `webdev`, but in something else (e.g. `angular_components`). I'm opening the issue here, because upgrading `webdev` and Dart to a new patch version shouldn't break things, IMO.

**Comment by kankaristo** [comment]
I've also tried using `build_runner` 1.5.0, and upgrading pretty much every package to the latest version, but nothing seems to work.

**Comment by jakemac53** [comment]
@nshahan it looks like we need a new version of angular_components which supports the latest build_config. I don't believe there were any breaking changes from the angular_components perspective.

**Comment by jakemac53** [comment]
In the meantime you can activate an older version of webdev to solve the immediate issue, `pub global activate webdev 2.0.5`. That will require build_daemon <1.0.0 so you would need to set that to limit your build_runner version to something compatible, but then it should work.

**Comment by stephan-gruen** [comment]
I don't use angular_components and I get as of today (without any changes in the pubspec.yaml):

"D:\dart-sdk\dart-sdk 2.3.1-dev.0.0\bin\pub.bat" get
Resolving dependencies...
Because no versions of angular match >5.3.0 <6.0.0 and angular 5.3.0 depends on build_config >=0.2.6 <0.4.0, angular ^5.3.0 requires build_config >=0.2.6 <0.4.0.
Because build_runner >=1.3.4 depends on build_config >=0.4.0 <0.4.1 and no versions of build_runner match >1.3.3 <1.3.4, build_runner >1.3.3 requires build_config >=0.4.0 <0.4.1.
Thus, angular ^5.3.0 is incompatible with build_runner >1.3.3.
And because build_runner 1.3.3 depends on build_daemon ^0.5.0 and gdv_simp_linechart_module depends on angular ^5.3.0, build_runner >=1.3.3 requires build_daemon ^0.5.0.
So, because gdv_simp_linechart_module depends on both build_runner ^1.3.3 and build_daemon ^1.0.0, version solving failed.`

**Comment by jakemac53** [comment]
Ah, so it looks like angular itself also needs to support the latest build_config, cc @matanlurey @alorenzen

**Comment by delizondo** [comment]
@jakemac53 also `angular_components` as it currently support `>=0.2.6 <0.4.0`

**Comment by bcc0421** [comment]
@kankaristo Try to upgrade ur dependencies:

> angular: '6.0.0-alpha'

It seems work for me, here is dev_dependencies:

> build_runner: '>=1.3.0 <2.0.0'
> build_web_compilers: '>=1.2.0 <3.0.0'
> build_daemon: ^1.0.0

**Comment by kankaristo** [comment]
@bcc0421, that still fails for `angular_components`, which doesn't seem to have an alpha available?

Also, I'd rather not use alpha versions (or even beta versions) in production apps, so I've downgraded `webdev` to 2.0.5 for the time being (thanks for the tip @jakemac53, I didn't know you could install older versions like that).

**Comment by DininduWanniarachchi** [comment]
@kankaristo Take a look at this may help,
https://stackoverflow.com/questions/56379418/angular-dart-build-fails-after-upgrade-dart

**Comment by kankaristo** [comment]
@DininduWanniarachchi, yeah, I already did that, it's working with `webdev` 2.0.5.

**Comment by alorenzen** [comment]
Angular is going to do a patch release of our 5.x branch to fix this. You can track that progress in https://github.com/dart-lang/angular/issues/1813

**Comment by stephan-gruen** [comment]
Hint for Windows devs:
As you now have to use build_web_compilers > 1.2.1 you will notice that version 2.x.x is NOT supported by the Windows platform. 
To solve this add stream_channel: ^2.0.0 to your dev_dependencies!
This works for me:

> angular_test: ^2.2.0
>   build_runner: ^1.5.0
>   build_test: ^0.10.6
>   build_web_compilers: 2.1.0
>   test: ^1.5.1
>   stream_channel: ^2.0.0

**Comment by jakemac53** [comment]
@stephan-gruen  build_web_compilers 2.x.x is supported windows - if you are experiencing an issue please file one.

**Comment by jakemac53** [comment]
Closing this issue as i believe it is now resolved

**Comment by alexander-doroshko** [comment]
@jakemac53 I'm afraid I'm still seeing the issue with webdev 2.0.7 (OS: Windows 10). Steps to reproduce - exactly as listed in the issue description. The error is: 
```
webdev could not run for this project.
The `build_runner` version – 1.3.3 – is not within the allowed constraint – >=1.5.0 <2.0.0.
```

**Comment by kankaristo** [comment]
With `webdev` 2.0.7 building the default stagehand project works with this `pubspec.yaml`:
```yaml
name: TestProject
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0-alpha.0
  pedantic: ^1.0.0
  test: ^1.5.1
```

However, I think it's odd that **alpha** versions `angular` and `angular_components` (and `build_web_compilers`?) are required to build with the latest **stable** Dart and `webdev`.

A beginner getting started with AngularDart would find everything completely broken, and would have no idea how to fix it. They'd think something is wrong with their install: it's the default project, it can't be broken, right? A beginner will not get through even the [basic setup](https://angulardart.dev/guide/setup).

IMO, `webdev` should be rolled back to 2.0.5. Either that, or the alpha versions of `angular` and `angular_components` should be quickly polished and made stable (and the basic tutorial and `stagehand` projects should also be updated).

Or should AngularDart not be used anymore ([dart.dev](https://dart.dev/) seems to be heavily focused on Flutter)?

**Comment by jakemac53** [comment]
> However, I think it's odd that **alpha** versions `angular` and `angular_components` (and `build_web_compilers`?)

The latest angular and build_web_compilers are fully compatible, the problem looks to be that angular_components only supports build_config 4.x with the latest alpha, which requires the latest alpha of angular. cc @nshahan 

> A beginner will not get through even the [basic setup](https://angulardart.dev/guide/setup).

I think they could because it doesn't require angular_components, but its true that things are painful right now.

> IMO, `webdev` should be rolled back to 2.0.5

This would cause a worse situation than we are in now, we would have even more possible combinations of packages to be concerned about and even more incompatibilities.

**Comment by kankaristo** [comment]
> 
> > A beginner will not get through even the [basic setup](https://angulardart.dev/guide/setup).
> 
> I think they could because it doesn't require angular_components, but its true that things are painful right now.

Ah, that's true, the [quickstart](https://github.com/angular-examples/quickstart/tree/master) project only required changing versions for `build_runner` and `build_web_compilers` in order to build. Although, a true beginner probably wouldn't know to fiddle about in `pubspec.yaml` (not sure if WebStorm helps with this, I don't use it).

**Comment by nshahan** [comment]
I just published angular_components v0.13.0+1 release that will build with the latest webdev.

**Comment by kankaristo** [comment]
Now the default `stagehand` project builds after changing these:
```
dependencies:
  angular_components: ^0.13.0

dev_dependencies:
  build_runner: ^1.5.0
```

Thanks! :tada:
