### ISSUE TITLE
FormatException: Unexpected character at "Not Found" when running daemon on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#514]
I'm not sure what's happening here, but on Windows when I run from VS Code I'm getting this error:

```
[13:38:06] [WebDaemon] [Info] <== [{"event":"daemon.log","params":{"log":"[INFO] Caching finalized dependency graph completed, took 257ms\n"}}]
[13:38:06] [WebDaemon] [Info] <== [{"event":"daemon.log","params":{"log":"[INFO] Succeeded after 29.5s with 562 outputs (3283 actions)\n"}}]
[13:38:06] [WebDaemon] [Info] <== [{"event":"daemon.log","params":{"log":"[INFO] ------------------------------------------------------------------------\n"}}]
[13:38:16] [WebDaemon] [Error] Unhandled exception:
[13:38:16] [WebDaemon] [Error] 
FormatException: Unexpected character (at character 1)
Not Found
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1259:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:924:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:493:36)
#5      JsonCodec.decode (dart:convert/json.dart:151:41)
#6      jsonDecode (dart:convert/json.dart:94:10)
#7      parse (package:source_maps/parser.dart:27:15)
#8      Sources.scriptParsed (package:dwds/src/debugging/sources.dart:55:19)
<asynchronous suspension>
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#15     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#16     WipDomain.eventStream.<anonymous closure>.<anonymous closure> (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)
#17     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

I'm running a pretty empty project from here:

https://github.com/Dart-Code/Dart-Code/tree/master/src/test/test_projects/flutter_web/hello_world

I've cleared my lockfile etc. and re-activated/pub get to get latest versions, but still see it.

**Comment by DanTup** [comment]
I fogot to mention - this doesn't seem to happen when I run from the terminal directly, but does 100% of the time when VS Code runs it. I haven't figured out what's different yet!

**Comment by DanTup** [comment]
Scratch that - it does happen from the terminal when using the same version of the SDK (I was using `2.5.0-dev.1.0.flutter-63120303a7` to get the failure).

**Comment by jakemac53** [comment]
I think this is probably fixed with the latest sdk, some issues around source maps have been fixed. Not sure if/when those got rolled into flutter though.

**Comment by jonahwilliams** [comment]
Do you know what the CL that would have fixed this is? I'm still seeing it on master

**Comment by jakemac53** [comment]
I don't know the cl, cc @grouma or @Markzipan might know.

I am going to work on at least handling 404 responses correctly though.

**Comment by grouma** [comment]
Here was the issue I opened:
https://github.com/dart-lang/sdk/issues/37364

**Comment by Markzipan** [comment]
I have a local repro of this issue. Doing some digging.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/webdev/pull/561 should help with issues like this (but it doesn't solve the underlying problem, just the handling of it when it occurs)

**Comment by Markzipan** [comment]
Thanks, Jake! That was extremely helpful.

Fix out here: https://github.com/dart-lang/webdev/pull/563
